name: 自托管运行器测试工作流

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置.NET环境（用户目录）
        uses: actions/setup-dotnet@v4
        with:
        dotnet-version: '8.0.x'
    
        dotnet-install-dir: "${{ runner.user }}/dotnet"

      - name: 验证.NET安装
        run: dotnet --version  # 检查是否安装成功

      - name: 还原依赖
        run: dotnet restore

      - name: 构建项目
        run: dotnet build --configuration Release
